/*
Package tfsrl is a generated package which contains definitions
of structs which represent a Terraform resource. 

This package was generated by ygocodegen
using the following YANG input files:
	- yang/srl
Imported modules were sourced from:
	- yang/ietf
*/
package tfsrl

import (
	"context"
	"time"

	"github.com/hashicorp/terraform-plugin-sdk/v2/diag"
	"github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema"
	log "github.com/sirupsen/logrus"
)

// resourceSystemSflowString function
func resourceSystemSflowString(d resourceIDStringer) string {
	return resourceIDString(d, "system_sflow")
}

// resourceSystemSflow function
func resourceSystemSflow() *schema.Resource {
	return &schema.Resource{
		CreateContext: resourceSystemSflowCreate,
		ReadContext:   resourceSystemSflowRead,
		UpdateContext: resourceSystemSflowUpdate,
		DeleteContext: resourceSystemSflowDelete,

		Importer: &schema.ResourceImporter{
			StateContext: schema.ImportStatePassthroughContext,
		},

		Timeouts: &schema.ResourceTimeout{
			Create: schema.DefaultTimeout(5 * time.Minute),
			Read:   schema.DefaultTimeout(5 * time.Minute),
			Update: schema.DefaultTimeout(5 * time.Minute),
			Delete: schema.DefaultTimeout(5 * time.Minute),
		},
		Schema: map[string]*schema.Schema{
        "sflow": {
            Type:     schema.TypeList,
            Optional: true,
            MaxItems: 1,
            Elem: &schema.Resource{
            	Schema: map[string]*schema.Schema{
                    "admin_state": {
                        Type:     schema.TypeString,
                        Optional: true,
                        Default: "disable",
                    },
                    "collector": {
                        Type:     schema.TypeList,
                        Optional: true,
                        MaxItems: 1,
                        Elem: &schema.Resource{
                        	Schema: map[string]*schema.Schema{
                                "collector_address": {
                                    Type:     schema.TypeString,
                                    Optional: true,
                                },
                                "collector_id": {
                                    Type:     schema.TypeInt,
                                    Required: true,
                                    ForceNew: true,
                                },
                                "network_instance": {
                                    Type:     schema.TypeString,
                                    Optional: true,
                                },
                                "port": {
                                    Type:     schema.TypeInt,
                                    Optional: true,
                                    Default: "6343",
                                },
                                "source_address": {
                                    Type:     schema.TypeString,
                                    Optional: true,
                                },
                            },
                        },
                    },
                    "sample_rate": {
                        Type:     schema.TypeInt,
                        Optional: true,
                        Default: "10000",
                    },
                    "sample_size": {
                        Type:     schema.TypeInt,
                        Optional: true,
                        Default: "256",
                    },
                },
            },
        },

        },
    }
}

func resourceSystemSflowCreate(ctx context.Context, d *schema.ResourceData, meta interface{}) diag.Diagnostics {
	log.Infof("Beginning Create: %s", resourceSystemSflowString(d))
	target := meta.(*Target)
	
	key := "sflow"

	p := "/system/sflow"
	v := "sflow"
	
	req, err := target.CreateSetRequest(&p, &v, d)
	if err != nil {
		return diag.FromErr(err)
	}

	response, err := target.Set(ctx, req)
	if err != nil {
		return diag.FromErr(err)
	}

	replaceInKeys(d.Get(v), "-", "_")
	log.Debugf("Set response: %v", response)

	d.SetId(key)
	return resourceSystemSflowRead(ctx, d, meta)
}

func resourceSystemSflowRead(ctx context.Context, d *schema.ResourceData, meta interface{}) diag.Diagnostics {
	log.Infof("Beginning Read: %s", resourceSystemSflowString(d))
	target := meta.(*Target)

	
	p := "/system/sflow"
	
	req, err := target.CreateGetRequest(&p, d)
	if err != nil {
		return diag.FromErr(err)
	}
	response, err := target.Get(ctx, req)
	if err != nil {
		return diag.FromErr(err)
	}

	log.Debugf("Get Gnmi read response: %v", response)

	return nil
}

func resourceSystemSflowUpdate(ctx context.Context, d *schema.ResourceData, meta interface{}) diag.Diagnostics {
	log.Infof("Beginning Update: %s", resourceSystemSflowString(d))
	target := meta.(*Target)
	
	key := "sflow"

	p := "/system/sflow"
	v := "sflow"
	

	req, err := target.CreateSetRequest(&p, &v, d)
	if err != nil {
		return diag.FromErr(err)
	}

	response, err := target.Set(ctx, req)
	if err != nil {
		return diag.FromErr(err)
	}

	replaceInKeys(d.Get(v), "-", "_")
	log.Debugf("Set response: %v", response)

	d.SetId(key)
	return resourceSystemSflowRead(ctx, d, meta)
}

func resourceSystemSflowDelete(ctx context.Context, d *schema.ResourceData, meta interface{}) diag.Diagnostics {
	log.Debugf("Beginning delete: %s", resourceSystemSflowString(d))
	target := meta.(*Target)

	
	p := "/system/sflow"
	
	req, err := target.CreateDeleteRequest(&p, d)
	if err != nil {
		return diag.FromErr(err)
	}

	response, err := target.Set(ctx, req)
	if err != nil {
		return diag.FromErr(err)
	}

	log.Debugf("Gnmi Delete Response: %v", response)

	d.SetId("")
	return nil
}
